# Generated by Django 6.0.5 on 2026-05-13 19:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AwardActual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award', models.CharField(choices=[('golden_boot', 'Bota de Oro (10 pts)'), ('golden_ball', 'Balón de Oro (10 pts)'), ('golden_glove', 'Guante de Oro (10 pts)'), ('young_player', 'Mejor Jugador Joven (5 pts)'), ('best_goal', 'Mejor Gol del Mundial (5 pts)')], max_length=20, unique=True)),
                ('player_name', models.CharField(blank=True, default='', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='BettingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('group_type', models.CharField(choices=[('family', 'Familia'), ('friends', 'Amigos')], max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(unique=True)),
                ('match_number', models.IntegerField()),
                ('round', models.CharField(choices=[('group', 'Fase de grupos'), ('round_of_32', 'Dieciseisavos'), ('round_of_16', 'Octavos'), ('quarter_final', 'Cuartos'), ('semi_final', 'Semifinal'), ('third_place', 'Tercer puesto'), ('final', 'Final')], max_length=20)),
                ('group_name', models.CharField(blank=True, default='', max_length=2)),
                ('home_team', models.CharField(max_length=80)),
                ('away_team', models.CharField(max_length=80)),
                ('stadium', models.CharField(blank=True, default='', max_length=200)),
                ('kickoff_utc', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Programado'), ('live', 'En vivo'), ('completed', 'Finalizado')], default='scheduled', max_length=20)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('last_synced', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['match_number'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('betting_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='inicio.bettinggroup')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('betting_group', 'name')},
            },
        ),
        migrations.CreateModel(
            name='KnockoutScorePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.CharField(choices=[('group', 'Fase de grupos'), ('round_of_32', 'Dieciseisavos'), ('round_of_16', 'Octavos'), ('quarter_final', 'Cuartos'), ('semi_final', 'Semifinal'), ('third_place', 'Tercer puesto'), ('final', 'Final')], max_length=20)),
                ('slot_top', models.CharField(max_length=20)),
                ('slot_bottom', models.CharField(max_length=20)),
                ('home_score', models.IntegerField()),
                ('away_score', models.IntegerField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knockout_scores', to='inicio.participant')),
            ],
            options={
                'unique_together': {('participant', 'slot_top', 'slot_bottom')},
            },
        ),
        migrations.CreateModel(
            name='GroupStandingPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=2)),
                ('team', models.CharField(max_length=80)),
                ('position', models.IntegerField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standing_predictions', to='inicio.participant')),
            ],
            options={
                'ordering': ['group_name', 'position'],
                'unique_together': {('participant', 'group_name', 'team')},
            },
        ),
        migrations.CreateModel(
            name='GroupMatchPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score', models.IntegerField()),
                ('away_score', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_predictions', to='inicio.match')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_predictions', to='inicio.participant')),
            ],
            options={
                'unique_together': {('participant', 'match')},
            },
        ),
        migrations.CreateModel(
            name='BracketPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=20)),
                ('team', models.CharField(max_length=80)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bracket_predictions', to='inicio.participant')),
            ],
            options={
                'ordering': ['slot'],
                'unique_together': {('participant', 'slot')},
            },
        ),
        migrations.CreateModel(
            name='AwardPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award', models.CharField(choices=[('golden_boot', 'Bota de Oro (10 pts)'), ('golden_ball', 'Balón de Oro (10 pts)'), ('golden_glove', 'Guante de Oro (10 pts)'), ('young_player', 'Mejor Jugador Joven (5 pts)'), ('best_goal', 'Mejor Gol del Mundial (5 pts)')], max_length=20)),
                ('player_name', models.CharField(max_length=120)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_predictions', to='inicio.participant')),
            ],
            options={
                'unique_together': {('participant', 'award')},
            },
        ),
    ]
